stages:          # List of stages for jobs, and their order of execution
  - test
image: cypress/base:12
unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - echo "installing again to make sure Cypress is installed"
    - npm install
    - npm run cy:run
    - echo "Code coverage is 90%"
